services:
  - type: web
    name: rotten-classifier-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    plan: free
    workingDir: backend
